version: "3.7"

services:
  item-app:
    image: diahputrilestari/item-app:v1
    command: sh -c "npm install --production --unsafe-perm && npm run build && npm start"
    ports:
      - 80:8080
    volumes:
      - ./:/app
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dicoding
      MONGO_INITDB_ROOT_PASSWORD: dicoding
      MONGO_INITDB_DATABASE: item-db

volumes:
  app-db:
